-- ============================================================
-- proposed_habits
-- Stores all habits generated by Architect before the user
-- picks which ones to start. Selected habits are copied to the
-- main habits table; unselected ones surface on Day 7.
-- ============================================================

create table if not exists proposed_habits (
  id         uuid    primary key default gen_random_uuid(),
  user_id    uuid    not null references auth.users(id) on delete cascade,
  habit_data jsonb   not null,
  selected   boolean not null default false,
  created_at timestamptz not null default now()
);

alter table proposed_habits enable row level security;

create policy "Users can manage own proposed habits"
  on proposed_habits for all
  using  (auth.uid() = user_id)
  with check (auth.uid() = user_id);
